### ISSUE TITLE
Absolute links in userChrome.css

### ISSUE THREAD

**Issue by nohm** [hdni/dotfiles#4]
You have used absolute paths for your images, e.g.;

list-style-image: url("file:///home/will/.mozilla/firefox/3z2gw6je.clean/chrome/assets/new-tab.png")!important;

This obviously won't work for others, convert them to base64/upload them please?

**Comment by hdni** [comment]
The icons had already been uploaded as assets.tar.gz, in the same repo as the userChrome.css.
You're definitely right, though, so I encoded them as base64 and pushed the new version. Thanks for bringing it up!
